-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 16:19:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chloe_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chloe_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chloe_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chloe_database` ;

-- -----------------------------------------------------
-- Table `chloe_database`.`acomodacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`acomodacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `nivel` VARCHAR(25) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `last_login` DATETIME NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtd_pessoas` INT UNSIGNED NOT NULL,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NOT NULL,
  `cupom` VARCHAR(45) NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `total_desconto` DECIMAL(10,2) NOT NULL,
  `confirmacao` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `data_confirmacao` DATETIME NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  `acomodacoes_id` INT NOT NULL,
  `servicos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `acomodacoes_id`, `servicos_id`),
  INDEX `fk_reserva_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_reserva_acomodacoes1_idx` (`acomodacoes_id` ASC) VISIBLE,
  INDEX `fk_reserva_servicos1_idx` (`servicos_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_acomodacoes1`
    FOREIGN KEY (`acomodacoes_id`)
    REFERENCES `chloe_database`.`acomodacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `chloe_database`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pontuacao` INT UNSIGNED NOT NULL DEFAULT 0,
  `descricao` LONGTEXT NULL,
  `status` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_avaliacoes_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacoes_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_item` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `qtd_item` INT UNSIGNED NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_consumo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` DECIMAL(10,2) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_consumo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_usuario10`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
